CFLAGS=-Wall	-g	-DNDEBUG

all:
	cc	 ex23.c -o ex23
clean:
	-rm	-f	ex23
#-Wall: enable all warnings
#-g: add debug symbols(inorder to use gdb symbols)
#-o: name of the of the output files to create
#-c: do not link
