CFLAGS=-Wall	-g	-DNDEBUG

all:
	cc	 ex26.c -o ex26
clean:
	-rm	-f	ex26
#-Wall: enable all warnings
#-g: add debug symbols(inorder to use gdb symbols)
#-o: name of the of the output files to create
#-c: do not link
