CFLAGS=-Wall	-g	-DNDEBUG

all:
	cc	 ex25.c -o ex25
clean:
	-rm	-f	ex25
#-Wall: enable all warnings
#-g: add debug symbols(inorder to use gdb symbols)
#-o: name of the of the output files to create
#-c: do not link
