CFLAGS=-Wall	-g	-DNDEBUG

all:
	cc	 ex24.c -o ex24
clean:
	-rm	-f	ex24
#-Wall: enable all warnings
#-g: add debug symbols(inorder to use gdb symbols)
#-o: name of the of the output files to create
#-c: do not link
